import { PALETTE } from './palette';

export const SEMANTIC_COLORS = {
  PRIMARY: {
    PURE: PALETTE.PRIMARY[500],
    LIGHT: PALETTE.PRIMARY[200],
    MID: PALETTE.PRIMARY[400],
    DARK: PALETTE.PRIMARY[900],
  },
  ACCENT: {
    PURE: PALETTE.ACCENT[500],
    LIGHT: PALETTE.ACCENT[100],
    MID: PALETTE.ACCENT[400],
    DARK: PALETTE.ACCENT[900],
  },
  NEUTRAL: {
    WHITE: PALETTE.NEUTRAL[100],
    BLACK: PALETTE.NEUTRAL[1000],
  },
  LOW: {
    PURE: PALETTE.NEUTRAL[700],
    LIGHT: PALETTE.NEUTRAL[800],
    MID: PALETTE.NEUTRAL[900],
  },
  HIGH: {
    PURE: PALETTE.NEUTRAL[400],
    LIGHT: PALETTE.NEUTRAL[300],
    MID: PALETTE.NEUTRAL[200],
  },
  SUCCESS: {
    PURE: PALETTE.SUCCESS[500],
    LIGHT: PALETTE.SUCCESS[200],
    MID: PALETTE.SUCCESS[400],
    DARK: PALETTE.SUCCESS[900],
  },
  WARNING: {
    PURE: PALETTE.WARNING[500],
    LIGHT: PALETTE.WARNING[200],
    MID: PALETTE.WARNING[400],
    DARK: PALETTE.WARNING[900],
  },
  DANGER: {
    PURE: PALETTE.DANGER[500],
    LIGHT: PALETTE.DANGER[200],
    MID: PALETTE.DANGER[400],
    DARK: PALETTE.DANGER[900],
  },
};
